### ISSUE TITLE
Function Titles

### ISSUE THREAD

**Issue by racheal2468** [slu-soc5650/lecture-11#3]
Both sets of binding functions are under titles that say "Bind Tabular Data" when the rbind function is for spatial data

**Comment by chris-prener** [comment]
hey @racheal2468 sorry I don't see this - can you give me a slide number? Thanks!

**Comment by racheal2468** [comment]
@chris-prener It's in the functions hand out. Sorry! I should have said that

**Comment by chris-prener** [comment]
oh got you - thanks @racheal2468 - it is fixed!
